
package atividade.pkg8;

import javax.swing.JOptionPane;

/**
 *
 * @author snootic
 */
public class Aluno extends javax.swing.JFrame {

    public Aluno() {
        super("Aluno");
        setVisible(true);
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dialogoFinal = new javax.swing.JDialog();
        NomeLabel = new javax.swing.JLabel();
        SobrenomeLabel = new javax.swing.JLabel();
        dataNascimentoLabel = new javax.swing.JLabel();
        CursoLabel = new javax.swing.JLabel();
        SexoLabel = new javax.swing.JLabel();
        labelRGM = new javax.swing.JLabel();
        nascData = new javax.swing.JTextField();
        Nome = new javax.swing.JTextField();
        Sobrenome = new javax.swing.JTextField();
        SexoNome = new javax.swing.JTextField();
        numeroRGM = new javax.swing.JTextField();
        CursoNome = new javax.swing.JTextField();
        nomeLabel = new javax.swing.JLabel();
        sobrenomeLabel = new javax.swing.JLabel();
        nascLabel = new javax.swing.JLabel();
        sexoLabel = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        sobrenomeField = new javax.swing.JTextField();
        nascField = new javax.swing.JFormattedTextField();
        mascRadio = new javax.swing.JRadioButton();
        femRadio = new javax.swing.JRadioButton();
        rgmLabel = new javax.swing.JLabel();
        cursoLabel = new javax.swing.JLabel();
        rgmField = new javax.swing.JFormattedTextField();
        cursoBox = new javax.swing.JComboBox<>();
        attButton = new javax.swing.JButton();

        NomeLabel.setText("Nome");

        SobrenomeLabel.setText("Sobrenome");

        dataNascimentoLabel.setText("Data de Nascimento");

        CursoLabel.setText("Curso");

        SexoLabel.setText("Sexo");

        labelRGM.setText("RGM");

        nascData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nascData.setEnabled(false);
        nascData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nascDataActionPerformed(evt);
            }
        });

        Nome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Nome.setEnabled(false);
        Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeActionPerformed(evt);
            }
        });

        Sobrenome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sobrenome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Sobrenome.setEnabled(false);

        SexoNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SexoNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        SexoNome.setEnabled(false);

        numeroRGM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numeroRGM.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        numeroRGM.setEnabled(false);

        CursoNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CursoNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CursoNome.setEnabled(false);

        javax.swing.GroupLayout dialogoFinalLayout = new javax.swing.GroupLayout(dialogoFinal.getContentPane());
        dialogoFinal.getContentPane().setLayout(dialogoFinalLayout);
        dialogoFinalLayout.setHorizontalGroup(
            dialogoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoFinalLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(dialogoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Nome)
                    .addComponent(dataNascimentoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SexoLabel)
                .addGap(94, 94, 94))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoFinalLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(NomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SobrenomeLabel)
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoFinalLayout.createSequentialGroup()
                .addGroup(dialogoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoFinalLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(labelRGM))
                    .addGroup(dialogoFinalLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(dialogoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nascData, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(numeroRGM))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(dialogoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoFinalLayout.createSequentialGroup()
                        .addComponent(CursoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoFinalLayout.createSequentialGroup()
                        .addGroup(dialogoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CursoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SexoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );
        dialogoFinalLayout.setVerticalGroup(
            dialogoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoFinalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(dialogoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLabel)
                    .addComponent(SobrenomeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(dialogoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNascimentoLabel)
                    .addComponent(SexoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nascData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SexoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(dialogoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRGM)
                    .addComponent(CursoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroRGM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CursoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomeLabel.setText("Nome");

        sobrenomeLabel.setText("Sobrenome");

        nascLabel.setText("Data de nascimento");

        sexoLabel.setText("Sexo");

        sobrenomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobrenomeFieldActionPerformed(evt);
            }
        });

        nascField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        mascRadio.setText("Masculino");

        femRadio.setText("Feminino");

        rgmLabel.setText("RGM");

        cursoLabel.setText("Curso");

        rgmField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        rgmField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgmFieldActionPerformed(evt);
            }
        });

        cursoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistemas de Informação", "Análise e Desenvolvimento de Sistemas", "Ciência da Computação", "Engenharia de Software", "Segurança da Informação", "Banco de Dados", "Gestão em Tecnologia da Informação" }));
        cursoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoBoxActionPerformed(evt);
            }
        });

        attButton.setText("Atualizar");
        attButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nascLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nascField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cursoBox, 0, 279, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sexoLabel)
                                    .addComponent(cursoLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mascRadio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(femRadio)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sobrenomeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sobrenomeField)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rgmLabel)
                            .addComponent(rgmField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(attButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(sobrenomeLabel)
                    .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sobrenomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(sexoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nascLabel)
                    .addComponent(nascField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mascRadio)
                    .addComponent(femRadio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgmLabel)
                    .addComponent(cursoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cursoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(attButton)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sobrenomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobrenomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sobrenomeFieldActionPerformed

    private void rgmFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgmFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgmFieldActionPerformed

    private void cursoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cursoBoxActionPerformed

    public String getNome(){
        return nomeField.getText();
    }
    
    public String getSobrenome(){
        return sobrenomeField.getText();
    }
    
    public String getRGM(){
        return rgmField.getText();
    }
    
    public String getDate(){
        return nascField.getText();
    }
    
    public void Dialogo(){
        String nome = getNome();
            String sobrenome = getSobrenome();
            String data = getDate();
            String RGM = getRGM();
            
            
            Nome.setText(nome);
            Sobrenome.setText(sobrenome);
            nascData.setText(data);
            SexoNome.setText("alo");
            numeroRGM.setText(RGM);
            CursoNome.setText("AAAA");
            dialogoFinal.setSize(370,300);
            dialogoFinal.setVisible(true);
    }
    
    
    private void attButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attButtonActionPerformed
        String confirmar = "Você está atualizando seus dados, deseja confirmar?";
        Integer confirm = JOptionPane.showConfirmDialog(rootPane, confirmar, "Atenção!", WIDTH);
        if (confirm == 2 || confirm == 1){
            
        }else if (confirm == 0){
            Dialogo();
        }
    }//GEN-LAST:event_attButtonActionPerformed

    private void NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeActionPerformed

    private void nascDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nascDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nascDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CursoLabel;
    private javax.swing.JTextField CursoNome;
    private javax.swing.JTextField Nome;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JLabel SexoLabel;
    private javax.swing.JTextField SexoNome;
    private javax.swing.JTextField Sobrenome;
    private javax.swing.JLabel SobrenomeLabel;
    private javax.swing.JButton attButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cursoBox;
    private javax.swing.JLabel cursoLabel;
    private javax.swing.JLabel dataNascimentoLabel;
    private javax.swing.JDialog dialogoFinal;
    private javax.swing.JRadioButton femRadio;
    private javax.swing.JLabel labelRGM;
    private javax.swing.JRadioButton mascRadio;
    private javax.swing.JTextField nascData;
    private javax.swing.JFormattedTextField nascField;
    private javax.swing.JLabel nascLabel;
    private javax.swing.JTextField nomeField;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField numeroRGM;
    private javax.swing.JFormattedTextField rgmField;
    private javax.swing.JLabel rgmLabel;
    private javax.swing.JLabel sexoLabel;
    private javax.swing.JTextField sobrenomeField;
    private javax.swing.JLabel sobrenomeLabel;
    // End of variables declaration//GEN-END:variables
}
